### ISSUE TITLE
[BUG]: Invalid SN on device dropdown menu

### ISSUE THREAD

**Issue by teras** [streamdeck-linux-gui/streamdeck-linux-gui#112]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

When I run the application, on the drop down list with the device name I see is:

**Stream Deck Mini - Invalid SN!**

This has the side-effect that, when I tried to load the configuration I had backed up, this wasn't accepted, since AFAIK the configuration is based on SN. I "hacked" it, by opening the `~/.streamdeck_ui.json` file, removing the saved `Invalid SN!` entry, renaming my original entry to `Invalid SN!` and launching again. But I believe this shouldn't be the way to do things.

### Steps to reproduce the behavior

Launch latest version of streamdeck 

The package was recently updated through my OS (I am using Arch linux). I am not sure if this was relevant or if something else happened.

### Expected behavior

To display/understand the SN of the device.

### System Information

* Arch linux rolling release
* Gnome 45.0
* Python 3.11.5

### Stream Deck Version

Mini

**Comment by teras** [comment]
Hello @dhtseany an honor to talk with you.
Regarding your questions:

1) Through yay. I am not sure that this is package related. To be honest, I was using the (previous version) application for quite some time, I was on a trip, came back, updated the system, launched the app, configuration was missing, and then I realized that the SN was missing.

2) I've opened this file already and "forced" change my configuration, from the "old" serial number, to serial number "Invalid SN!". This worked, but the bug remains. It had 2 sections, one with the original SN, and one with the faulty "Invalid SN!" entry. Right now has (by hand) only the "Invalid SN!" entry.

3) This is what I thought too, but the device gets recognized properly, send events etc and even change things from the command line. My udev rule at `/etc/udev/rules.d/70-streamdeck.rules` is as follows:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", TAG+="uaccess", MODE:="666"
```

Thank you again

**Comment by teras** [comment]
My bad, I should have already stated the actual package. Is the `streamdeck-ui`. 

Out of curiosity I tried also the other three
* `streamdeck-ui-git` 3.2.0.r0.g2e67068-1
* `streamdeck-ui-beta` 3.2.0.beta.1-1
* `streamdeck-ui-develop` r571.c6dd6e3-1

All of them had the same problem, manifesting SN as `Invalid SN!`.

Now I remembered that, one of the reason I was using the specific package, and not a "newer" one, was exactly this problem. With the "historical" streamdeck-ui package the SN was there, but on the development packages the SN was not.

It seems, since now things have advanced, all packages now have the *same* problem.

**Comment by 4s3ti** [comment]
well ... If you tried the develop one you might have gotten in trouble. 
develop has changes that are not backwards compatible as the state file schema changed significantly. 

I suspect that something on your config might have gotten screwed up with some changes back and forth in the past.

**Comment by teras** [comment]
With all respect, doesn't seem a config issue for me. Even if I delete the `~/.streamdeck_ui.json` file and start from scratch, the SN is still not recognized.

It more looks like something prevents the software from reading the SN from the device, even though in the past this was possible.

**Comment by teras** [comment]
Maybe I should have added a screenshot in the first place. I am doing this now.
With a clean start, without `~/.streamdeck_ui.json` file, this is what I see:

![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/592568/bdcfb690-476c-4ef3-a810-08bc4b4ef634)

**Comment by 4s3ti** [comment]
My apologies then, maybe I missed that detail, but now with that info it changes everything. are you using any USB hub in between? 

I don't have a streamdeck mini to test that unfortunately to try to replicate the issue. 

Iif you open a terminal and start the aplication from the terminal with `streamdeck` does it return any error?

**Comment by teras** [comment]
No, directly on my pc's usb ports. When I tried through a hub (in the past) the power was not enough and the device wasn't recognized. Again as I was saying, the application works perfectly fine. All events are sent etc etc, the only problem is since the SN is not recognized, configuration is on the *wrong* place.

To minimize the possible noise, I started streamdeck with a blank configuration.
Indeed now I see some errors I didn't see before:

```
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
Exception in thread Thread-4 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/display/display_grid.py", line 138, in _run
    page = self.pages[self.current_page]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 6
```

**Comment by 4s3ti** [comment]
Now that gives some hints to work with. @rkmax maybe you want to take a look at it?

**Comment by rkmax** [comment]
if the application is working normally with the exceptions
- UI showing the wrong SN
- the error whe is connected for first time: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/issues/112#issuecomment-1787588124
 
- I might have an idea what's is happening but @teras if you could please do:

- backup your configuration file
- delete the configuration file
- start the app
- attach the configuration file

that will help me to fix the problem without assumtions

**Comment by 4s3ti** [comment]
@rkmax The stack trace is already on a fresh start of the application without any prior configuration.

**Comment by rkmax** [comment]
@teras @4s3ti unluckily the stack trace is not useful to fix the issue

you can ignore the `qt.qpa.input.events` 


```
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
qt.qpa.input.events: scroll event from unregistered device 35
Exception in thread Thread-4 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/display/display_grid.py", line 138, in _run
    page = self.pages[self.current_page]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 6
```

that's why I asked for the .json file from teras. I want to get answered the question:  was the real SN stored in any place of the .json file?


if the answer is yes, I want to see the value  and in what places of the .json file was stored correctly and what places not
Example 
![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/f8c7ce6d-07c2-48af-880d-3cef5cfa54eb)

if the answer is no. the value stored  "Invalid SN!"? or what was the stored value?

if the "Invalid SN!" present in the UI is also the same stored in the in the JSON. is an issue of the upstream library https://github.com/abcminiuser/python-elgato-streamdeck but probably you still can use the app because the serial is "Invalid SN!"

**Comment by teras** [comment]
_was the real SN stored in any place of the .json file?_

No, the .json file stored the text `Invalid SN!` as a serial number.
And yes, I can still use the app without any problem.

The reason I opened this bug request, is because still this is a bug and maybe needs to be addressed somehow :smile: 

So practically you are telling me that it's a library problem? Should I contact the upstream developer of the library for this? Was there any change on the library useage during the last weeks?

**IMPORTANT NOTE!** When I first tried this application, the "non-devel" version didn't have this problem while the "devel" problem had. If both used the same (version of the)  library, maybe the problem is somewhere else.

**Comment by rkmax** [comment]
> _was the real SN stored in any place of the .json file?_
> 
> No, the .json file stored the text `Invalid SN!` as a serial number. And yes, I can still use the app without any problem.
> 
> The reason I opened this bug request, is because still this is a bug and maybe needs to be addressed somehow 😄
> 
> So practically you are telling me that it's a library problem? Should I contact the upstream developer of the library for this? Was there any change on the library useage during the last weeks?
> 
> **IMPORTANT NOTE!** When I first tried this application, the "non-devel" version didn't have this problem while the "devel" problem had. If both used the same (version of the) library, maybe the problem is somewhere else.

thank you for the clarification note. maybe I missed that part in all previous messages,and due to that I tought it was a problem with the upstream library related to the support with your specific device, and also in the fact that  since I start to made changes to the package the logic involved in recognizing the device is untoched

of course that's something to fix. but is due the nature of linux systems that are a lot of moving parts, kernels, system dependencies, 3rd party libraries. 

after double check the source code of this app, check the upstream libreary code, the hidapi source code trying to figure a place where that problem happens but nothing  so I retract my recommendation. Instead double check the  your system dependencies and permissions (urules, etc), ensure your devices is connected in a USB port that is supported for the driver

For example, I'm also using arch these are the versions of the libraries installed in my system

- kernel: 6.5.8-arch1-1
- hidapi 0.14.0-2
- qt6-base 6.6.0-2


maybe you can use dmesg to diagnoticate how the device is interacting with your current system configuration

Example

```
[49864.385616] input: Elgato Stream Deck MK.2 as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:0FD9:0080.0026/input/input62
[49864.443025] hid-generic 0003:0FD9:0080.0026: input,hidraw1: USB HID v1.10 Device [Elgato Stream Deck MK.2] on usb-0000:00:14.0-1/input0
[49866.121726] usb 1-1: USB disconnect, device number 24
[49866.475287] usb 1-1: new high-speed USB device number 25 using xhci_hcd
[49866.598702] usb 1-1: Device not responding to setup address.
[49866.805393] usb 1-1: Device not responding to setup address.
[49867.015307] usb 1-1: device not accepting address 25, error -71
[49887.664973] usb 1-1: new high-speed USB device number 27 using xhci_hcd
[49887.806051] usb 1-1: New USB device found, idVendor=0fd9, idProduct=0080, bcdDevice= 4.40
[49887.806067] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[49887.806074] usb 1-1: Product: Stream Deck MK.2
[49887.806080] usb 1-1: Manufacturer: Elgato
[49887.806084] usb 1-1: SerialNumber: DL47L2A40266
```

any additional informacion that may help yo diagnoticate the issue and see if it's something that we can fix in the code of the app

but

**Comment by teras** [comment]
You are right. It's a kernel issue. Not an app issue.
Still, I don't need how to handle it.
`dmesg` shows this log:

```
[   52.332603] usb 1-1.2: new high-speed USB device number 20 using xhci_hcd
[   52.441029] usb 1-1.2: New USB device found, idVendor=0fd9, idProduct=0090, bcdDevice= 1.10
[   52.441047] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   52.441052] usb 1-1.2: Product: Stream Deck Mini
[   52.441056] usb 1-1.2: Manufacturer: Elgato Systems
[   52.441060] usb 1-1.2: SerialNumber: Invalid SN! 
[   52.445929] input: Elgato Systems Stream Deck Mini as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2/1-1.2:1.0/0003:0FD9:0090.000F/input/input31
[   52.501447] hid-generic 0003:0FD9:0090.000F: input,hidraw14: USB HID v1.10 Device [Elgato Systems Stream Deck Mini] on usb-0000:00:14.0-1.2/input0
```

It's clear to me that the kernel doesn't recognize the Serial Number. How can I approach it?

Kernel 6.6.1-arch1-1
hidapi 0.14.0-2
python-hidapi 0.14.0-1
qt6-base 6.6.0-3

Thank you for your support. I have to say you're probably the most polite OS group I ever talked with.

**Comment by teras** [comment]
Hello guys.

Can you help me, what should I do so that the kernel can properly read the Serial Number? 

Thank you!

**Comment by dend** [comment]
@teras just adding another datapoint here, since I am building [DeckSurf](https://deck.surf) - this seems like a common challenge with Stream Deck Mini _specifically_ - it's likely not a problem with the kernel or any OS component, but rather how Stream Deck Mini itself is "baked":

![Stream Deck Mini in the Stream Deck software](https://github.com/user-attachments/assets/6a4478f8-84b6-49d3-9209-dadf1b3828b3)

**Comment by coolapso** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203
