### ISSUE TITLE
[BUG]: Can't configure any button. Error in terminal when a button is clicked

### ISSUE THREAD

**Issue by iDaddyCz** [streamdeck-linux-gui/streamdeck-linux-gui#197]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

First fresh instalation of stremdeck-linux-gui on Debian SID. The gui opens and is able to correctly load my StreamDeck XL and Stream Deck +. When I click any button on the boar nothing happens in the UI and I can't set anything.
In the terminal I see the following error:

```
Traceback (most recent call last):
  File "/home/idaddy/.local/share/pipx/venvs/streamdeck-linux-gui/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 941, in <lambda>
    lambda current_button=button, all_buttons=buttons: button_clicked(current_button, all_buttons)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/idaddy/.local/share/pipx/venvs/streamdeck-linux-gui/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 499, in button_clicked
    if not selected_button.isChecked():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'isChecked'
```

Adding some debug code confirms that selected_button is indeed a boolean with the value `true`

### Steps to reproduce the behavior

1. Open the Gui
2. Click any button on the board

### Expected behavior

The configuration box for the button should be editable.

### Screenshots

![Screenshot from 2024-04-09 20-46-40](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/97808271/cbbd7dc9-69c0-49da-940a-6cb1fc4d3f3f)

### System Information

OS: Debian GNU/Linux trixie/sid x86_64 
Kernel: 6.7.9-amd64 
Uptime: 27 mins 
Packages: 4534 (dpkg), 19 (flatpak), 12 (snap) 
Shell: zsh 5.9 
Resolution: 5120x1440 
DE: GNOME 44.9 
WM: Mutter 
WM Theme: Default 
Theme: Adwaita [GTK2/3] 
Icons: gnome [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 7950X3D (32) @ 5.759GHz 
GPU: AMD ATI 12:00.0 Raphael 
GPU: NVIDIA GeForce RTX 4090 
Memory: 6121MiB / 95761MiB 

### Stream Deck Version

StreamDeck XL
Stream Deck +

**Comment by Sigurs** [comment]
Same issue here

StreamDeck XL
Python 3.12.2
Linux fedora 6.8.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr  4 20:45:21 UTC 2024 x86_64 GNU/Linux

**Comment by v4u6h4n** [comment]
Maybe same for me, with min, #200 probably a duplicate.

@Sigurs

Did you already have it installed? I've had mine running fine for months...

**Comment by Sigurs** [comment]
@v4u6h4n completely new installation in my case.

I have an another machine (Ubuntu LTS) where I'm running the original one from around a year ago.

**Comment by v4u6h4n** [comment]
I can select buttons now, however the button pressing on the physical streamdecks is now broken. I can't really determine exactly what is happening, except that it seems every button press presses at least one different button. For example pressing button 3 will press button 2 once or twice. (Also I ended up trying the build steps using the aur git repo)

**Comment by 4s3ti** [comment]
Believe that is now another bug, and may need another issue with errors and what not. 

If its an option and you don't have much things to migrate,  recommend you trying [streamcontroller](https://github.com/StreamController/StreamController) and open issues for any functionality you may have missing. 

Also there may be an effort to find a easy path to migrate from one to the other.

**Comment by v4u6h4n** [comment]
@4s3ti 

I've got a lot to migrate, but StreamController looks really cool, so I'll see if I can get it done over the next few days and be a guinea pig for the new project lol

Thanks for the help :-)

**Comment by 4s3ti** [comment]
@v4u6h4n sure you're perfect candidate to test this: https://github.com/StreamController/StreamController/issues/32 

:)
