### ISSUE TITLE
[BUG]: Error scaning device

### ISSUE THREAD

**Issue by marvin1099** [streamdeck-linux-gui/streamdeck-linux-gui#224]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

The program "steamdeck" (the UI) reports a error when starting the connection to the steamdeck.
It will report:
```
Unable to set font: /usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-BlackItalic.ttf
Unable to set font: /usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-BlackItalic.ttf
Unable to set font: /usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-BoldItalic.ttf
Unable to set font: /usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-BoldItalic.ttf
Unable to set font: /usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-BlackItalic.ttf
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
self.run()
File "/usr/lib/python3.12/threading.py", line 1010, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.12/site-packages/streamdeck_ui/stream_deck_monitor.py", line 117, in _run
self.attached(streamdeck_id, streamdeck)
File "/usr/lib/python3.12/site-packages/streamdeck_ui/api.py", line 203, in _on_steam_deck_attached
self._update_streamdeck_filters(serial_number)
File "/usr/lib/python3.12/site-packages/streamdeck_ui/api.py", line 658, in _update_streamdeck_filters
self._update_button_filters(serial_number, page, button)
File "/usr/lib/python3.12/site-packages/streamdeck_ui/api.py", line 701, in _update_button_filters
display_handler.replace(page, button, filters)
File "/usr/lib/python3.12/site-packages/streamdeck_ui/display/display_grid.py", line 97, in replace
pipeline_filter.initialize(self.size)
File "/usr/lib/python3.12/site-packages/streamdeck_ui/display/image_filter.py", line 90, in initialize
frame = frame.resize((int(v * scale_factor) for v in frame.size), Image.LANCZOS)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 2305, in resize
im = im.resize(size, resample, box)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 2328, in resize
return self._new(self.im.resize(size, resample, box))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 1 must be 2-item sequence, not generator
```
after a few seconds of loading

### Steps to reproduce the behavior

1. Have version 4.1.2.r4.g0f42d50d-1
2. Run steamdeck
3. Wait

### Expected behavior

My steamdeck should be listed (since its listed in lsusb)

### Screenshots

![Screenshot_20240708_200000](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/40715852/4b91150c-7ecb-4654-a8ad-d6118202d6fb)

### System Information

OS: Arch based
Destop: KDE
Python Version: Python 3.12.4 
Im also using the arch repo git version

### Stream Deck Version

Standard

**Comment by zeroedin-shawn** [comment]
Issue seems related to last weeks update to PIL library on Python: https://github.com/python-pillow/Pillow/commit/6990fc4a0996753c5faa6cc272b753cac23cffdf

Changes to the type hint might have broke support, and need conversion to a tuple: https://github.com/python-pillow/Pillow/issues/8195

Annoying, but a temporary fix is to downgrade PIL (python-pillow) to 10.3.0-2. 
@marvin1099: If you haven't yet, since you are Arch-based, you should be able to pull that version from here until it's fixed: https://archive.archlinux.org/packages/p/python-pillow/

**Comment by coolapso** [comment]
Hi, please read: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203

**Comment by thyme-87** [comment]
Thanks for the clarity about the project status @coolapso !

Fixed this (for now) by changing line 90 in `/usr/lib/python3.12/site-packages/streamdeck_ui/display/image_filter.py`:

```sh
-            frame = frame.resize((int(v * scale_factor) for v in frame.size), Image.LANCZOS)
+            frame = frame.resize(tuple(int(v * scale_factor) for v in frame.size), Image.LANCZOS)
```

based on [this](https://github.com/python-pillow/Pillow/pull/3087#discussion_r181572707) discussion in Pillow.

Unfortunately there are still too many issues for me with streamcontroller.

**Comment by coolapso** [comment]
If you care to open  PR I could try to make a fix release for that.

**Comment by thyme-87** [comment]
@coolapso 

1. For `streamcontroller` I ran into a lot of missing dependencies not noted in the requirements.txt. Finally ending in pypi package `install` missing which since seems to have been blocked on pypi package index: https://pypi.org/project/install/ (see: https://github.com/pypi/support/issues/451) - working around that issue was possible - I might open a PR at some point to add the missing dependencies. (After this experience, I refuse using flatpack to install `streamcontroller`)
2. I started working on a fix, but after updating pillow to `10.3.0` to address security warnings from the linter, I ran into issues related to typing in multiple other places. Started fixing those but unfortunately I don't have enough time to see this through - encouraging others to continue working on this.

**Comment by coolapso** [comment]
>  For streamcontroller I ran into a lot of missing dependencies not noted in the requirements.txt. Finally ending in pypi package install missing which since seems to have been blocked on pypi package index: https://pypi.org/project/install/ (see: https://github.com/pypi/support/issues/451) - working around that issue was possible - I might open a PR at some point to add the missing

hmm, yeah if you are trying to install build it like that, probably there are some issues ... Flatpak is your best bet. 

as for the rest .. the codebase of this project is hard to get into, hence the migration to streamcontroller.

**Comment by Core447** [comment]
@thyme-87 
Hi, I'm one of the developers of StreamController! First of all thanks for the feedback. Idk what exactly happened to the `install` module, but we removed the dependency of it. Regardless of this I highly recommend using the Flatpak for day to day use.

**Comment by thyme-87** [comment]
@coolapso @Core447 first of all, thanks for your fast reply here.
Please do not take it as a negative comment or attitude towards you or the `StreamController` project - which overall makes a good impression.
As a result of my take on installing it locally, I'll raise a PR with the missing dependencies that I encountered on my system. However, this experience also led me to believe, that the build and release process for `StreamController` is yet involving certain manual steps and/or a manually maintained build system. And for that reason I will keep checking in on building and installing it locally for now.

**Comment by Core447** [comment]
> [Edit: can't reproduce the missing dependencies. So apparently I made something wrong during the initial setup. All the best for the `StreamController` project]

Thank you!

**Comment by coolapso** [comment]
Believe [v4.1.3](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v4.1.3)  fixes this issue. Please check and let me know

**Comment by marvin1099** [comment]
Jep it works now.
I will keep both progamms around maby.
For me Streamcontroller running from source works great, not the flatpac though.
