### ISSUE TITLE
[BUG]: xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by malinkb** [streamdeck-linux-gui/streamdeck-linux-gui#67]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

The streamdeck gui starts, but I can't configure anything

This is the output from the terminal:

```
[malinux@caffeine streamdeck-linux-gui]$ streamdeck
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1709, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/malinux/.local/lib/python3.11/site-packages/streamdeck_ui/stream_deck_monitor.py", line 113, in _run
    self.attached(streamdeck_id, streamdeck)
  File "/home/malinux/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 195, in attached
    self.update_streamdeck_filters(serial_number)
  File "/home/malinux/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 584, in update_streamdeck_filters
    self.update_button_filters(serial_number, page, button)
  File "/home/malinux/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 628, in update_button_filters
    display_handler.replace(page, button, filters)
  File "/home/malinux/.local/lib/python3.11/site-packages/streamdeck_ui/display/display_grid.py", line 79, in replace
    filter.initialize(self.size)
  File "/home/malinux/.local/lib/python3.11/site-packages/streamdeck_ui/display/image_filter.py", line 33, in initialize
    png = cairosvg.svg2png(svg_code, output_height=size[1], output_width=size[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malinux/.local/lib/python3.11/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malinux/.local/lib/python3.11/site-packages/cairosvg/surface.py", line 129, in convert
    tree = Tree(
           ^^^^^
  File "/home/malinux/.local/lib/python3.11/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malinux/.local/lib/python3.11/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1711, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

```

### Steps to reproduce the behavior

1. Follow the install guide for Arch Linux/Manjaro
3. When installed, launch the streamdeck gui from terminal
4. See terminal output
5. Same output if I build and install version 3.1.0 from source. Also happens if I build from latest git

### Expected behavior

I expceted the stream deck gui to start and to be able to add buttons

### Screenshots

![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/1184892/8881b06d-7922-4516-be16-f4c4593b8ac6)

### System Information

* Arch Linux
* KDE
* python 3.11

### Stream Deck Version

Standard

**Comment by rkmax** [comment]
Can you check please the if the file `~/.streamdeck_ui.json` exists, try to rename it like `mv ~/.streamdeck_ui.json ~/.streamdeck_ui.json.bk` then try to open the app again if that solves the issue means ~/.streamdeck_ui.json include a icon that's not a valid image and the apllicacion is trying to convert from SVG

but still it looks like some additional error handling need to be placed to avoid this happen

**Comment by malinkb** [comment]
Hi
That actually worked.

Thanks a lot <3

Sincere

Malinux <3


Sent with Proton Mail secure email.

------- Original Message -------
